### ISSUE TITLE
Install instruction. 

### ISSUE THREAD

**Issue by dhruvbatra** [allenai/robothor-challenge#4]
> ./scripts/build.sh

Requires sudo.

**Comment by ekolve** [comment]
I believe I have fixed your issue.  I removed the dependency on bc and ran this on an AWS instance with the AWS deep learning AMI without requiring sudo. Please confirm when you have a chance.

thanks,
eric

**Comment by dhruvbatra** [comment]
Nope, still seeing problems without sudo. Probably because docker daemon was started as root?

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/2941091/74680236-cddb9f00-5174-11ea-8b95-9818d5e4d97e.png">

**Comment by ekolve** [comment]
Ahh, what I suspect is happening for you is that your user is not in the docker group.  

The docker docs recommend adding users to the docker group to allow commands to be run without sudo.
https://docs.docker.com/install/linux/linux-postinstall/

I think a sensible thing for the build.sh then would be to check whether the user (if not sudo/root) is in the docker group and if not emit a message to either run as sudo or add the user to the docker group.

Sound good?

**Comment by dhruvbatra** [comment]
Yes.

**Comment by ekolve** [comment]
./scripts/build.sh has been updated to check for docker, whether the user is root (running as sudo) or in the docker group.  Informative errors are printed if any of the aforementioned checks fail.
